### ISSUE TITLE
Change the project description

### ISSUE THREAD

**Issue by camilosw** [sadmb/ofxKinectNui#13]
The project description say "Kinect SDK beta2 addon for openFrameworks ". Change to "Kinect SDK 1.0...." so others viewing the openframeworks addons page know that this work with the 1.0 version.

Do you have plans to support the SDK 1.5?

**Comment by sadmb** [comment]
ooops, thx @camilosw !
i thought it would change automatically corresponding to readme.md.

As I use with 1.5 and it works out-of-the-box. : )

Please try and let me know if any problem.

Thanks!

sadam
