### ISSUE TITLE
@sadmb Can you check the function getDistancePixels()

### ISSUE THREAD

**Issue by leezhm** [sadmb/ofxKinectNui#14]
@sadmb I found that there are some problem with getDistancePixels(), Bellow is my code

```
// set the depth pixels
cv::Mat ofxMatKinectDepth(DepthWidth, DepthHeight, CV_16UC1, KinectSensor.getDistancePixels().getPixels());

    cv::Mat kinectDepth8;
double maxVal, minVal;
cv::minMaxLoc(ofxMatKinectDepth, &minVal, &maxVal, NULL, NULL);

ofxMatKinectDepth.convertTo(kinectDepth8, CV_8UC1, 255.0 / maxVal);

    // show KinectDepth8
```

When i show the kinectDepth8, the whole image was divided into 4 blocks and every blocks had the sample pixels.

**Comment by sadmb** [comment]
Mmm, i don't know the reason... but if you want to get 8bit depth pixels, you just call getDepthPixels() instead of getDistancePixels().
Please let me know if you find solution.

**Comment by leezhm** [comment]
@sadmb  this is my problem.Ｓｏｒｒｙ！
