### ISSUE TITLE
slow calibrated pixels

### ISSUE THREAD

**Issue by Kj1** [sadmb/ofxKinectNui#19]
Hey,

If i enable the calibrated rgb image (initSetting.grabCalibratedVideo = true;) the framerate drops drastically from 30 to 10. (an update takes +- 90ms instead of 10 ms)

I saw it iterates over every depth pixel to get the calibrated rgb coordinate.  Now the MS SDK has a method for doing this on a frame basis (NuiImageGetColorPixelCoordinateFrameFromDepthPixelFrameAtResolution). gotta love those names. check here for an example:

http://kinectcomposite.codeplex.com/wikipage?title=Converting%20Depth%20Frame%20coordinates%20to%20Color%20Frame%20coord.

I've implemented this and now i'm getting the full 30hz framerate for the calibrated image.  Editded code attached.  My c++ knowledge is limited so I very much assume you can speed it up even more (memcopy tricks etc).

The code changes are  I am also a github noob...

Cheers,
Kj

kinect/nui/kinect.h; add  
LONG\* GetDepthMappedRGBFrameCoordinates();

kinect/nui/kinect.cpp add

LONG\* Kinect::GetDepthMappedRGBFrameCoordinates()
{

```
//todo make this work for all resolutions
int depthResX = 640, depthResY = 480;
int depthSpaceSize = depthResX*depthResY;
USHORT *depthPixels = (USHORT*) malloc( 2 * depthResX * depthResY * sizeof(USHORT) );

int colorResX = 640, colorResY = 480;
LONG *mappedCoords = (LONG*) malloc( 2 * colorResX * colorResY * sizeof(LONG) );

sensor_->NuiImageGetColorPixelCoordinateFrameFromDepthPixelFrameAtResolution(
    VideoStream().Resolution(),     // color resolution
    DepthStream().Resolution(),     // depth resolution
    depthResX*depthResY,            // number of depth values
    depthPixels,                    // pointer to depth values array
    2*colorResX*colorResY,          // number of color coordinates
    mappedCoords                    // pointer to color coordinates array
);
return mappedCoords;
```

}

ofxKinectNui.cpp; 
comment out the "if(flag & UPDATE_FLAG_CALIBRATED_VIDEO) {" block.

Add just above  "if(flag & UPDATE_FLAG_GROUP_SKELETON){" (so it runs only once per image and not per depth pixel)

if((flag & UPDATE_FLAG_GROUP_DEPTH) && (flag & UPDATE_FLAG_CALIBRATED_VIDEO)) {

```
LONG *mappedCoords = kinect.GetDepthMappedRGBFrameCoordinates();

unsigned char* calibPixels = calibratedVideoPixels.getPixels();
unsigned char* videoPixelsRaw = videoPixels.getPixels();

for(int i=0; i < 640*480; i++) {
    int i3 = i * 3;
    int i2 = i * 2;

    int calibCoord = 3*(mappedCoords[i2] + mappedCoords[i2+1]*640);

    if (calibCoord > 640*480*3 || calibCoord < 0) 
        calibCoord = 0;


    calibPixels[i3++] = videoPixelsRaw[calibCoord++];
    calibPixels[i3++] = videoPixelsRaw[calibCoord++];
    calibPixels[i3++] = videoPixelsRaw[calibCoord++];

}
```

}

**Comment by sadmb** [comment]
Hi @Kj1 
Great thanks for your commitment. ; )
Yeah, now I am checking there, I will update ASAP!

cheers,

sadam

**Comment by Kj1** [comment]
you're welcome!

I've already found some issues with my code/style :)
Memory leak: LONG *mappedCoords needs to be deleted after usage and USHORT *depthPixels also
depth & width are hardcoded for my setup
not the most efficient memcopy way of doing thinks.

looking forward to learn from your improvements :)

**Comment by sadmb** [comment]
@Kj1 
Sorry for late update.
I've just changed calibrated video part. ; )
Please check if it's enough efficient and close this issue.

Again, thanks for your report!

**Comment by Kj1** [comment]
Thanks, that does the trick!
