### ISSUE TITLE
ofxKinectNui in of0.80 not work correctly.

### ISSUE THREAD

**Issue by yty** [sadmb/ofxKinectNui#20]
void AudioStream::Open(AEC_SYSTEM_MODE mode /*= OPTIBEAM_ARRAY_ONLY */)
{

HRESULT ret = mediaObject_->ProcessOutput(0, 1, &outputBufferStruct_, &dwStatus);  //=〉In this line crashes ...
}

vs2012 +of0.80

**Comment by viniciolindo** [comment]
instead i have this error with two GetProcessInformation function in two different class process.h and a quicktime .h file

Error   7   error C2733: 'GetProcessInformation' : second C linkage of overloaded function not allowed  c:\users\giulio\desktop\of_v0.8.0_vs_release\libs\quicktime\include\processes.h 195 1   kinectNuiExample

i use windows 8 with visual studio express 2012 and openframeworks 0.8

**Comment by inundaciones** [comment]
I also have the same error:
Error 7 error C2733: 'GetProcessInformation' : second C linkage of overloaded function not allowed 
I'm on windows 7, visual studio express 2012 and OF 8.0

**Comment by sadmb** [comment]
Hello guys,
Thanks for comments and sorry for late reply.
It's kinda busy month this month...
I will update asap. : )

Please let me know if you can solve the problem.

**Comment by timmb** [comment]
It seems that the Quicktime library included with oF 0.8 is incompatible with <windows.h> in version 8 of the Windows SDK. Both Processes.h and Winbase.h try to define GetProcessInformation.

Adding macro guards around the Processes.h definition seems to work for me:

```
// Tim: Avoid incompatibility with Winbase.h (included with windows.h)
#ifndef _WINBASE_
EXTERN_API( OSErr )
GetProcessInformation           (const ProcessSerialNumber * PSN,
                                 ProcessInfoRec *       info)                               THREEWORDINLINE(0x3F3C, 0x003A, 0xA88F);
#endif
```

Of course it's not ideal to need to edit the main oF project, or indeed the QuickTime SDK files. Works for us as a short term fix. But long term I think this is an issue that will need to be raised on the openFrameworks project.

**Comment by sadmb** [comment]
@timmb 

Great! Thanks a lot for sharing your solution.
Mmm, I heard QuickTime is about to change to AV Kit on new Mac so possibly it would be competing with the old code.
For the sound part, I bring from official Kinect SDK on version1.6 or something so I should check it with newest version.

Thanks!

**Comment by sadmb** [comment]
Guys,

Sorry for late.
I have upgraded it to VS2012 + OF 0.8.0 or OF 0.8.1 compatible.

Still you have to fix GetProcessInformation issue that @timmb mentioned.

Thanks!
