### ISSUE TITLE
depth doesn't update correctly (with fix)

### ISSUE THREAD

**Issue by mfargo** [sadmb/ofxKinectNui#3]
I was having problems with getting depth frames (notably, when NOT using grabLabel).

I managed to fix it by changing line 395 of ofxKinectNui::update from:
    depthbit = depth(depth.Width() - x, y);
to:
    depthbit = depth(depth.Width() - x, y) >> 3;

**Comment by sadmb** [comment]
Hello Matthew,
Sorry for this late because of my pc was crashed. : (
I will update ASAP!!
Thx
