### ISSUE TITLE
clipping params don't do anything?

### ISSUE THREAD

**Issue by jeffcrouse** [sadmb/ofxKinectNui#4]
It's super useful that the near/far clipping distance is stored in the recorded data files, etc., but they don't seem to be used anywhere in any of the ofxKinectNui\* clases).  Perhaps this was a planned feature that just didn't make it?  

So, I'd like to make 2 changes in a pull request:
1. Right now, the code that populates ofxKinectNui::skeletonPoints (which is what is returned by ofxKinectNui::getSkeletonPoints()) is in the ofxKinectNui::drawSkeleton() function.  This is a problem because if you don't call drawSkeletons(), the points that you get from getSkeletonPoints() will be incorrect.  It seems that this should be moved to update()
2. Clipping tests (using nearClippingDistance and farClippingDistance) should be added into ofxKinectNui::update() and ofxKinectNuiPlayer::update()

Sound good? Am I missing something obvious?

**Comment by sadmb** [comment]
Hello jeff,
Sounds nice, yeah! : )
Thanks so much. I appreciate your help!
