### ISSUE TITLE
Deadlock in KinectContext::ShutdownAll()

### ISSUE THREAD

**Issue by lucieb** [sadmb/ofxKinectNui#5]
I am programming an application using ofxKinectNui on Windows and I keep running in an issue where closing the window causes my application to freeze.

I think the problem is a deadlock in the function ShutdownAll in the class KinectContext. 

void KinectContext::ShutdownAll()
{
    lock_.lock(); // <---------
    int size = (int)kinects_.size();
    for(int i = 0; i < size; i++){
        Shutdown(*kinects_[i]); // but Shutdown(..) also tries to lock un lock_
    }
    lock_.unlock(); // <---------
}

void KinectContext::Shutdown(Kinect& kinect)
{
    if(IsConnected(kinect.index_)){
        lock_.lock(); // <----- is waiting for lock_ but it is already locked in ShutdownAll = deadlock
        std::wcout << "Shutdown Kinect[" << kinect.index_ << "], Device Name:: " << kinect.uniqueId_ << "\n" << std::endl;
        kinect.sensor_->NuiShutdown();
        lock_.unlock();
    }
}

Let me know if I'm wrong!

**Comment by sadmb** [comment]
Great!
I really want to solve this freeze problem.
I've just got my fixed PC.
So I will check! : )
I will update some bugs too.

Thx.

sadmb

**Comment by nariakiiwatani** [comment]
Thanks for reporting!
I've fixed the problem on today's commit.
Please pull latest and check it!

nariakiiwatani
