### ISSUE TITLE
DepthStream().Width() - Division by zero

### ISSUE THREAD

**Issue by imanhabib** [sadmb/ofxKinectNui#6]
Hi,

I found a division by zero bug that only happened when compiling in release-mode and running the application .exe outside of visual studio.

In file: https://github.com/sadmb/ofxKinectNui/blob/master/src/kinect/nui/Kinect.cpp

Insert this:

```
if ( DepthStream().Width() == 0 )
return -1;
```

Before these lines:

```
        lDepthX = (LONG)(lDepthPixel % DepthStream().Width());
        lDepthY = (LONG)(lDepthPixel / DepthStream().Width());
```

Cheers
// Iman

**Comment by sadmb** [comment]
Hello iman,
Thx so much for informing. : )

I wil check ASAP!

sadam

**Comment by sadmb** [comment]
I've just forgot fix this.
Now it's fixed. : )
Thx so much for your help, iman.
