### ISSUE TITLE
# Something wrong with getCalibratedVideoPixels()

### ISSUE THREAD

**Issue by leezhm** [sadmb/ofxKinectNui#9]
If I set the resolution of video and depth image is 640 x 480, I got a wrong image with getCalibratedVideoPixels().

But if we set it as 320 x 240, that will be prefect.

**Comment by sadmb** [comment]
Thx, leezhm. : )
I will check now and fix it asap.

**Comment by sadmb** [comment]
OK, fixed. : )
(it was because old version of SDK didn't allow other resolution than 320x240 for calibrated video, so I changed NuiImageGetColorPixelCoordinatesFromDepthPixel to NuiImageGetColorPixelCoordinatesFromDepthPixelAtResolution on Kinect.cpp)
Please try again.

**Comment by leezhm** [comment]
@sadmb Thanks, It works well now.
